"""renamed place_id

Revision ID: 15e81fe28ef1
Revises: 4e1332f2209c
Create Date: 2026-04-24 12:14:27.125089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e81fe28ef1'
down_revision: Union[str, Sequence[str], None] = '4e1332f2209c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('place', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('Events_place_id_fkey'), 'Events', type_='foreignkey')
    op.create_foreign_key(None, 'Events', 'places', ['place'], ['id'])
    op.drop_column('Events', 'place_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('place_id', sa.UUID(), autoincrement=False, nullable=True))
   # op.drop_constraint('fk_events_place_id', 'Events', type_='foreignkey')
    op.create_foreign_key(op.f('Events_place_id_fkey'), 'Events', 'places', ['place_id'], ['id'])
    op.drop_column('Events', 'place')
    # ### end Alembic commands ###
