"""add ticket model

Revision ID: 4c9d4df8e501
Revises: 092b3f8e7c66
Create Date: 2026-04-27 12:11:15.859383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9d4df8e501'
down_revision: Union[str, Sequence[str], None] = '092b3f8e7c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event', sa.UUID(), nullable=False),
    sa.Column('seat', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event'], ['Events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
