"""rename field place

Revision ID: ef5821c96a1d
Revises: 15e81fe28ef1
Create Date: 2026-04-24 19:03:41.516815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5821c96a1d'
down_revision: Union[str, Sequence[str], None] = '15e81fe28ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('place_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('Events_place_fkey'), 'Events', type_='foreignkey')
    op.create_foreign_key(None, 'Events', 'places', ['place_id'], ['id'])
    op.drop_column('Events', 'place')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('place', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Events', type_='foreignkey')
    op.create_foreign_key(op.f('Events_place_fkey'), 'Events', 'places', ['place'], ['id'])
    op.drop_column('Events', 'place_id')
    # ### end Alembic commands ###
